apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: azure-get-secret-test
  title: Display Array of Strings
  description: A template that takes an array of strings and displays each value.
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Input Strings
      required:
        - secretNames
      properties:
        secretNames:
          type: array
          title: Provide an Array of Secret Names
          description: Enter a list of strings
          items:
            type: string

  steps:
    - id: get-azure-secrets
      name: Get Azure Key Vault Secrets
      action: azure-key-vault:getSecrets
      input:
        secretNames: "{{ parameters.secretNames }}"

    - id: log-fetched-values
      name: log fetch secrets output
      action: debug:log  
      input: 
         message: ${{steps.get-azure-secrets.output.results}}  

  output:
    text:
      - title: Strings Displayed
        content: |
          The input strings were displayed in the logs.
